default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fullstack_challenge_development

test: &test
  <<: *default
  database: fullstack_challenge_test

cucumber:
  <<: *test
